### ISSUE TITLE
android编译的so不可用

### ISSUE THREAD

**Issue by tuyazuo** [yaukeywang/slua-503-build#1]
hello,不知有没有测试过android真机，我最近用你提供的项目编了试下，编译ok，但真机器上无法识别DllNotFoundException
我使用的是ndk r10b (64-bit)，用gcc4.9编译，api为androidL

**Comment by yaukeywang** [comment]
我很久没更新了，但是我当时是在真机都测试过的，不过我是直接用 vs2015编译的，当时用的ndk是32位，我觉得应该还是编译器的问题，有时间我打算重新更新下。

**Comment by tuyazuo** [comment]
hi,昨天测试发现是手机问题，我编的是armeabi-v7a的，分别在三星、lg上测试，lg的会无法识别。
但是这两款手机的cpu架构都是支持 armeabi-v7a的，不知道是不是某些编译参数问题导致的

**Comment by yaukeywang** [comment]
http://www.cnblogs.com/yaukey/p/slua-530-compile-project.html
这是我之前记录的编译参数的博客，目前项目时间太紧实在没有时间去查看，后面我有更新会告诉你，你试试 https://github.com/yaukeywang/2DPlatformer-SLua 这个项目能跑不，这个是基于这个项目我编译的slua5.3库移植的游戏。

**Comment by tuyazuo** [comment]
thanks,终于搞明白问题了，我之前用的64位ndk，编出来的是64位库，在很多安卓机上不支持，换了32位ndk就好了。 我把项目换成了用命令行编译，果然遇到很多问题，你的博客给了很大帮助！
试了下你那个项目，运行正常

**Comment by yaukeywang** [comment]
解决就好，你也分享出来给更多需要的人帮助吧~

**Comment by yaukeywang** [comment]
Hi @tuyazuo ，我突然想起来个问题，你编译的64位的库，在打包的时候是否跟32位的库分开在特定的目录放置，比如你的64位的库，放在了32位的库目录下，在安卓的apk中，64位的库应该放在 "arm64-v8a" 中而不是 “armeabi-v7a” 中，用此方法试试你自己编译的64位库。
具体你也可以看看 https://github.com/yaukeywang/2DPlatformer-SLua/tree/master/Assets/Plugins/Android/libs 这下面的文件夹布局，分别包含了安卓的 arm 32/64 位，x86 32/64位。

**Comment by tuyazuo** [comment]
嗯，这个我也试过，应该还是cpu不支持64位的问题，我用5.4.1的unity，现在只支持两个库，armv7和x86， 64位处理器可以向下兼容
